kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ include "nekoui.fullname" . | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    helm.sh/chart: {{ include "nekoui.chart" . | quote }}
    app.kubernetes.io/name: {{ include "nekoui.name" . | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
  {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.deployment.replicas | int }}
  revisionHistoryLimit: {{ .Values.deployment.revisionHistoryLimit | int }}
{{- if gt (.Values.deployment.replicas | int) 1 }}
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
{{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "nekoui.name" . | quote }}
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "nekoui.name" . | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
      {{- with .Values.labels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      annotations:
        kubectl.kubernetes.io/default-container: app
        checksum/conf: {{ pick (include (print $.Template.BasePath "/configmap.yaml") . | fromYaml) "data" | toYaml | sha256sum | quote }}
      {{- with .Values.deployment.revision }}
        revision: {{ . | quote }}
      {{- end }}
      {{- with .Values.deployment.annotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
    {{- with .Values.deployment.affinity }}
      affinity: {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.deployment.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- if .Values.image.credentials }}
      imagePullSecrets:
        - name: {{ printf "%s.registry" (include "nekoui.fullname" .) | quote }}
    {{- end }}
      containers:
        - name: app
          image: {{ printf "%s:%s" .Values.image.repository .Values.image.tag | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: conf
              subPath: nginx.conf
              mountPath: /etc/nginx/conf.d/default.conf
              readOnly: true
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 5
        {{- with .Values.deployment.resources }}
          resources: {{- toYaml . | nindent 12 }}
        {{- end }}
      volumes:
        - name: conf
          configMap:
            name: {{ printf "%s.conf" (include "nekoui.fullname" .) | quote }}
