{{- if .Values.image.credentials }}
{{- $cred := .Values.image.credentials }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ printf "%s.registry" (include "nekoui.fullname" .) | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    helm.sh/chart: {{ include "nekoui.chart" . | quote }}
    app.kubernetes.io/name: {{ include "nekoui.name" . | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
  {{- with $.Values.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf `{"auths":{%s:{"auth":"%s"}}}` ($cred.registry | quote) (printf "%s:%s" $cred.username $cred.password | b64enc) | b64enc | quote }}
{{- end }}
