name: nekoui
description: Neko tamagochi-like game.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.1.0-alpha.1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  audioplayers: ^1.0.0-rc.4
  badges: ^2.0.3
  bordered_text: ^2.0.0
  circular_menu: ^2.0.0
  collection: ^1.16.0
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_local_notifications: ^10.0.0-dev.16
  geolocator: ^9.0.0
  get: ^4.6.5
  google_fonts: ^3.0.1
  hive_flutter: ^1.1.0
  hive: ^2.1.0
  js: ^0.6.4
  mutex: ^3.0.0
  page_transition: ^2.0.5
  path_provider: ^2.0.10
  rive: ^0.8.4
  toml: ^0.12.0
  timezone: ^0.8.0
  sentry_flutter: ^6.5.1
  universal_io: ^2.0.4
  uuid: ^3.0.6
  yaml: ^3.1.0

dev_dependencies:
  build_runner: ^2.1.10
  dartdoc: ^5.0.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^1.1.2

flutter:
  uses-material-design: true
  
  assets:
    - assets/conf.toml
    - assets/fonts/
    - assets/images/background/
    - assets/images/furniture/
    - assets/images/item/
    - assets/images/neko/
    - assets/images/room/
    - assets/images/ui/
    - assets/rive/
    - pubspec.yaml

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
