name: nekoui
description: Neko tamagotchi-like game.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.1.0-alpha.1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  audioplayers: ^1.0.0-rc.4
  badges: ^2.0.3
  bordered_text: ^2.0.0
  circular_menu: ^2.0.0
  collection: ^1.16.0
  fluent:
    git: https://github.com/sagudev/fluent-dart.git
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_local_notifications: ^10.0.0-dev.18
  geolocator: ^9.0.0
  get: ^4.6.5
  google_fonts: ^3.0.1
  hive_flutter: ^1.1.0
  hive: ^2.1.0
  http: ^0.13.4
  js: ^0.6.4
  mutex: ^3.0.0
  novel:
    # path: ../novel
    git:
      url: https://github.com/SleepySquash/novel.dart.git
      ref: improve-implementation
  page_transition: ^2.0.5
  path_provider: ^2.0.10
  rive: ^0.8.4
  toml: ^0.12.0
  timezone: ^0.8.0
  sentry_flutter: ^6.5.1
  universal_io: ^2.0.4
  uuid: ^3.0.6
  yaml: ^3.1.0

dev_dependencies:
  build: ^2.3.0
  build_runner: ^2.1.10
  dartdoc: ^5.0.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^1.1.2

flutter:
  uses-material-design: true
  
  assets:
    - assets/background/
    - assets/character/
    - assets/conf.toml
    - assets/font/
    - assets/item/
    - assets/l10n/
    - assets/location/floor/
    - assets/location/furniture/
    - assets/location/furniture/
    - assets/neko/
