name: CI

on:
  push:
    branches: ["main"]
    tags: ["v*"]
  pull_request:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FLUTTER_VER: "3.0"

jobs:

  ################
  # Pull Request #
  ################

  pr:
    if: ${{ github.event_name == 'pull_request' }}
    needs:
      - build
      - dartdoc
    runs-on: ubuntu-latest
    steps:
      - run: true



  
  ############
  # Building #
  ############

  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: apk
            artifacts: build/app/outputs/flutter-apk/app-*.apk
          - platform: appbundle
            artifacts: build/app/outputs/bundle/release/app-release.aab
          - platform: linux
            artifacts: build/linux/x64/release/bundle
          - platform: windows
            artifacts: build/windows/runner/Release
          - platform: web
            artifacts: build/web
    runs-on: ${{ ((matrix.platform == 'ios' || matrix.platform == 'macos')
                                                  && 'macos-latest')
                 || (matrix.platform == 'windows' && 'windows-latest')
                 || (matrix.platform == 'linux'   && 'ubuntu-22.04')
                                                  || 'ubuntu-latest' }}
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: $FLUTTER_VER
          channel: stable
          cache: true
      - run: sudo apt-get update -y
        if: ${{ matrix.platform == 'linux' }}
      - run: sudo apt-get install -y
             ninja-build
             libunwind-dev
             libgtk-3-dev
             libgstreamer1.0-dev
             libgstreamer-plugins-base1.0-dev
             libpulse-dev
        if: ${{ matrix.platform == 'linux' }}
      - run: flutter config --enable-${{ matrix.platform }}-desktop
        if: ${{ matrix.platform == 'linux'
                || matrix.platform == 'macos'
                || matrix.platform == 'windows' }}
      - run: make flutter.pub
      - run: make flutter.build platform=${{ matrix.platform }}
             split-per-abi=yes
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.platform }}
          path: ${{ matrix.artifacts }}
          if-no-files-found: error
  
  dartdoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: $FLUTTER_VER
          channel: stable
          cache: true
      - run: make flutter.pub
      - run: make docs.dart clean=yes
      - uses: actions/upload-artifact@v3
        with:
          name: docs
          path: doc/api




  #############
  # Releasing #
  #############
  
  gh-pages:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    needs:
      - dartdoc
    steps:
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
      - uses: actions/download-artifact@v3
        with:
          name: docs
          path: main
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./main
          destination_dir: main
          commit_message: ${{ github.event.head_commit.message }}
          keep_files: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'

  release:
    name: Release on GitHub
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    needs: ["build"]
    steps:
      - uses: actions/checkout@v3
      - name: Verify tag matches version
        run: test "${{ github.ref_name }}" == "v$(make flutter.version)"
      - run: make github.release.notes
             project-url="${{ github.server_url }}/${{ github.repository }}"
             > ./release_notes.md

      - uses: actions/download-artifact@v3
        with:
          name: apk
          path: android/
      - uses: actions/download-artifact@v3
        with:
          name: appbundle
          path: android/
      - uses: actions/download-artifact@v3
        with:
          name: web
          path: web/
      - uses: actions/download-artifact@v3
        with:
          name: windows
          path: windows/
      - uses: actions/download-artifact@v3
        with:
          name: linux
          path: linux/
      - uses: actions/download-artifact@v3
        with:
          name: docs
          path: docs/
      
      - run: mkdir package
      - run: ls -R

      - uses: thedoctor0/zip-release@main
        with:
          type: 'zip'
          filename: 'package/nekoui-windows-x86_64.zip'
          path: windows
      - uses: thedoctor0/zip-release@main
        with:
          type: 'zip'
          filename: 'package/nekoui-linux-x86_64.zip'
          path: linux
      - uses: thedoctor0/zip-release@main
        with:
          type: 'zip'
          filename: 'package/nekoui-web.zip'
          path: web
      - uses: thedoctor0/zip-release@main
        with:
          type: 'zip'
          filename: 'package/docs.zip'
          path: docs

      - run: mv android/app-arm64-v8a-release.apk package/nekoui-arm64-v8a.apk
      - run: mv android/app-armeabi-v7a-release.apk package/nekoui-armeabi-v7a.apk
      - run: mv android/app-x86_64-release.apk package/nekoui-x86_64.apk
      - run: mv android/app-release.aab package/nekoui.aab

      - name: Generate SHA256 checksums
        run: ls -1 | xargs -I {} sh -c "sha256sum {} > {}.sha256sum"
        working-directory: package/
      - name: Show generated SHA256 checksums
        run: cat *.sha256sum
        working-directory: package/

      - uses: ncipollo/release-action@v1
        with:
          artifacts: |
            package/*.apk
            package/*.aab
            package/*.zip
            package/*.sha256sum
          allowUpdates: true
          artifactErrorsFailBuild: true
          name: ${{ github.ref_name }}
          bodyFile: ./release_notes.md
          token: ${{ secrets.GITHUB_TOKEN }}
