name: CI

on:
  push:
    branches: ["main"]
    tags: ["v*"]
  pull_request:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  ARTIFACT_PREFIX: nekoui
  FLUTTER_VER: "3.0"

jobs:
  release-docker:
    name: Release Docker image
    runs-on: ubuntu-latest
    env:
      IMAGE: nekoui
      REPOS: ghcr.io/sleepysquash
      TAGS: latest,@versions
    steps:
      - uses: actions/checkout@v3

      - name: Parse semver versions from Git tag
        id: semver
        uses: actions-ecosystem/action-regex-match@v2
        with:
          text: ${{ github.ref }}
          regex: '^refs/tags/v((([0-9]+)\.[0-9]+)\.[0-9]+(-.+)?)$'
        if: ${{ contains(env.TAGS, '@versions') }}
      - run: echo ${{ steps.semver.outputs.group1 }}
      - run: echo ${{ steps.semver.outputs.group2 }}
      - run: echo ${{ steps.semver.outputs.group3 }}
      - run: echo ${{ steps.semver.outputs.group4 }}
      - run: echo ${{ steps.semver.outputs.group5 }}
      - name: Prepare final image tags
        id: tags
        uses: bluwy/substitute-string-action@v1
        with:
          _input-text: ${{ env.TAGS }}
          "@versions": ${{ steps.versions.outputs.result }}

